#168237345 add readme file on repository and also edit link in swagger documentation
kimenyikevin/FreeMentor pull request #38
Opened 2019-09-02 12:03 UTC by kimenyikevin

#### What does this PR do?
- have readme on the root folder of repository and working APIs documentation
#### Description of Task to be completed?
 have the following works properly 
- The ReadMe on the root of the repository
- documentation be able to fetch data on Heroku
#### How should this be manually tested?
- visit FreeMentor repository to see ReadMe 
- And also click on this link to view documentation https://freementorss.herokuapp.com/api-docs/
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#168237345
#### Screenshots (if appropriate)
#### Questions:

2019-09-02 18:58 UTC, Kasulejoseph requested changes

2019-09-02 18:58 UTC, Kasulejoseph commented on .nyc_output/processinfo/index.json
> -{"processes":{"74f192e6-021f-4eec-8b7f-6bf437be94e5":{"parent":null,"children":[]}},"files":{"C:\\my properties\\now\\andela's document\\BootComp\\FreeMentor\\server\\test\\authTest.js":["74f192e6-02
Add this file in the `.gitignore` it shouldn't be pushed

2019-09-03 05:19 UTC, kimenyikevin commented
### I am done with  that untracked file moved to gitigore

2019-09-03 13:11 UTC, Kasulejoseph approved these changes
Looks good.

2019-09-03 13:13 UTC, merged